<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\rapid.erp.Common\rapid.erp.Common.csproj" />
    <ProjectReference Include="..\rapid.erp.EntityModel\rapid.erp.EntityModel.csproj" />
  </ItemGroup>

</Project>
